### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by pentool** [survivejs/webpack#101]
Hi, I have a comment on the website itself (survivejs.com). Would be nice to adjust the breakpoints on the site so that it's convenient the read on a standard 13" laptop screen. Eg, using a MacBook Pro 13" laptop, even with the browser maximized, the site layout is as follows (starting from top to bottom):
1. There's GIGANTIC image at the top that covers nearly, I'd say, 80% of the screen. So you pretty much don't see any content (aside from the huge image with "Getting Started" on it) so you need to scroll down.
2. Once you scrolled down a little, the sidebar (with the TOC) cannot fit next to the content due to a breakpoint issue, so what you see is the sidebar on the left and a huge empty space in the content area. This continues until you scroll down and reach the end of the TOC.
3. Then, after more scrolling, you see the two books being advertised on top of each other.
4. And finally, after a mile of scrolling, you see the content finally appear on the page.

When I view the site on a 27" monitor where I can expand the browser's width, at some point the desktop breakpoint will kick in and the sidebar (TOC) will sit next to the content area so it provides a better overall experience.

But please adjust the breakpoints of the site layout so it can be viewed without issues on a 13" screen (since there are quite a few 13" laptops out there).

Thanks!

**Comment by bebraw** [comment]
Those are valid points. I'm actually on a 13" display myself but I can see what you mean after adjusting the browser size a bit.

I can definitely tone down the header. Maybe 50% of the current size or so. The rest takes more thinking.

I'll do some initial tweak in a bit and we can go from there.

**Comment by bebraw** [comment]
Hi,

I simplified it a notch on low resolutions. Give it a go and let me know what you think. 👍

**Comment by pentool** [comment]
Thanks for the speedy update, but now the menu is not visible at all anywhere on a 13" screen!

When you maximize your browser window (safari, chrome, ff) on a 13" screen, the menu is gone. Of course (usually) there are different resolutions can be set for a monitor. I am using the default resolution on my 13" macbook pro which is 2560x1600 @2x (so technically 1280x800).

**Comment by bebraw** [comment]
Yeah, the reasoning was that on lower resolution it might make sense to provide a simplified experience. Now that I think of it, maybe one way to handle it would be to change the order so that you get the content first, toc, and the rest after. Or I could redesign the breakpoints a notch.

**Comment by pentool** [comment]
Ideally there should be no issues having a sidebar and content visible next to each other on a 13" screen. I guess a sidebar/TOC hanging by itself is still better than no TOC :-) But this way even if I open the site on an XYZ size monitor and the browser just happen to be at a 1280 width size, the TOC won't be visible, which gives the impression there's no other content on the site.

**Comment by bebraw** [comment]
Yeah, that's a fair point. I think I'll try to tweak it so that you get a nice sidebar with 1280 px width.

**Comment by bebraw** [comment]
Moved to https://github.com/survivejs/site/issues/44 .
