### ISSUE TITLE
Discuss various debugging flags

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack#12]
``` bash
--profile
--progress --profile --colors --display-modules
```

**Comment by christianalfoni** [comment]
Yeah, and the difference between `--devtool eval` and the others

**Comment by bebraw** [comment]
One more to discuss: `--display-reasons`.

**Comment by bebraw** [comment]
Analyse tool - http://webpack.github.io/analyse/ operates based on `stats.toString({reasons: true}).toJson()` (not 100% sure where to invoke that but it's probably easy to figure out).

**Comment by bebraw** [comment]
Stats etc. should be covered now.
