### ISSUE TITLE
Typo/bug in Building with Webpack/ 04 - Processing with Babel

### ISSUE THREAD

**Issue by Velenir** [survivejs/webpack#127]
In [Processing with Babel](https://github.com/survivejs/webpack/blob/dev/manuscript/building_with_webpack/04_processing_with_babel.md) chapter **webpack.parts.js** includes:

```js
use: 'babel-loader',

options: {/* ... */}
```

But running `npm run build` with this config throws `Error: options/query provided without loader (use loader + options)`. It seems **options** property requires **loader** property to be present:
either

```js
loader: 'babel-loader',
options: {/* ... */}
```

or

```js
use: [{
  loader: 'babel-loader',
  options: {/* ... *}
}]
```

Just `use: 'babel-loader'` without **options** works perfectly.

**Comment by bebraw** [comment]
Yeah, this should be fixed now. Just noticed it myself. Thanks for the heads up!
