### ISSUE TITLE
Linting JavaScript chapter - missing block in code snippet

### ISSUE THREAD

**Issue by jeggett** [survivejs/webpack#132]
"Connecting ESLint with Webpack" section. Code listing named "webpack.config.js".

Because now this chapter goes after a chapter in which we pluged HMR to our configuration, we probably can add this missing snippet from previous chapter:
```
    parts.devServer({
      // Customize host/port here if needed
      host: process.env.HOST,
      port: process.env.PORT
    }),
```
right before `parts.lintJavaScript(PATHS.app)` snippet.

**Comment by bebraw** [comment]
I'm not so sure. I pushed `parts.lintJavaScript(PATHS.app)` to `const common` block on purpose so that it gets applied on all targets. This is nice as then possible CI would lint too.

I noticed some ellipsis was missing on the example, though, so I added that so that it's clearer.

**Comment by jeggett** [comment]
Yes, sorry. I haven't noticed `const common` in the beginning. And because there is not ellipsis in the bottom of the listing I put it to the `module.exports` part.

**Comment by bebraw** [comment]
No probs. It should be clearer now. 👍
