### ISSUE TITLE
Linting JavaScript chapter - ELIFECYCLE error

### ISSUE THREAD

**Issue by jeggett** [survivejs/webpack#133]
I got  `ELIFECYCLE error` in terminal if linting errors is present when I run `npm test:lint` after completing the chapter (the only difference is I used airbnb preset). See https://github.com/eslint/eslint/issues/2409 
What if we add `;exit 0` at the end of the `"test:lint": "eslint . --cache"` entry in the `scripts` section of `package json` or is there another more graceful way?

**Comment by bebraw** [comment]
Can you push your project to GitHub so I can have a closer look?

**Comment by jeggett** [comment]
https://github.com/jeggett/webpack2_config PS. I use ubuntu 16.04

**Comment by bebraw** [comment]
Can you try `npm run test:lint -s` or `npm run test:lint --silent`? You should still see linting errors to fix, but that should eliminate `ELIFECYCLE`.

**Comment by jeggett** [comment]
Yes, `--silent` eliminates the error.

**Comment by bebraw** [comment]
Btw, you can run `node_modules/.bin/eslint . --fix` to fix the most.

**Comment by bebraw** [comment]
Alright. I think I'll tweak the chapter so that these points are clearer (silent/autofix).

**Comment by jeggett** [comment]
`--fix` was clear, but I haven't noticed '--silent' in the chapter.

**Comment by jeggett** [comment]
Oh, I should read the version from repo, not from the survive.js site so I do not point you on things you have already changed/fixed.

**Comment by bebraw** [comment]
Nah, it's alright. I'm actually doing silent releases now so it stays more or less up to date. ;)

**Comment by jeggett** [comment]
Probably this `ELIFECYCLE` error is not an issue but correct behavior, because it make commit-hooks like `husky` and `precommit` you mentioned in the chapter to proc.
