### ISSUE TITLE
Loading Images chapter - suggestion

### ISSUE THREAD

**Issue by jeggett** [survivejs/webpack#138]
"Setting Up url-loader" section. You write "If you use the limit option, you will need to install both url-loader and file-loader to your project. ". I think it's worth  mentioning not to use them both in config, because it will corrupt loaded images. I didn't know this and googled 20 mins to figure out what is happening.

**Comment by bebraw** [comment]
Ah, great point. It's definitely either/or. Multiple matches would be bad indeed.
