### ISSUE TITLE
Hash handling

### ISSUE THREAD

**Issue by christianalfoni** [survivejs/webpack#14]
Have to finish to section

https://github.com/webpack/file-loader is mentioned as a loader that can automatically update your index.html with the new hash

**Comment by bebraw** [comment]
Probably safe to close now. Feel free to re-open if you want to expand on the idea. There's a [chapter about hashing](http://survivejs.com/webpack/building-with-webpack/adding-hashes-to-filenames/) so this type of content would fit there.
