### ISSUE TITLE
error against the book content 

### ISSUE THREAD

**Issue by h2m2** [survivejs/webpack#145]
I am referring to 

https://github.com/survivejs/webpack/blob/dev/manuscript/developing_with_webpack/02_automatic_browser_refresh.md

(Why on earth are you moxing in leanpub? With a completely new syntax from a completely new space? )

The given webpack.config.js is erroring out.  
const common is unknown. 

const common = {
      ^^^^^^
SyntaxError: Unexpected identifier

The provided javascript is unreliable. 
Even without the leanpub injections. 
This is the second webpack.config.js and it is already a mess with publishing mixed in , without correct package.json, with errors in the js. 

Brrrr, it is getting cold.

**Comment by bebraw** [comment]
Hi,

Which version of Node are you using?

Why are you reading from GitHub? There's a [web version](http://survivejs.com/webpack/introduction/) and [ebook](https://leanpub.com/survivejs-webpack).

> This is the second webpack.config.js and it is already a mess with publishing mixed in , without correct package.json, with errors in the js.

Can you point out specific errors? I cannot fix them otherwise. The chapter expects you have gone through the earlier ones.

**Comment by h2m2** [comment]
Hi , 
it is okay. 

The error is due to the injection of leanpub in your git documentation.
In that sense: I am correct.
BUT: I am not correct. If you would pull your book from it, ..... there must be certain important things different. I can see this from the number of brackets that are opening and closing and so.... I found somewhow through. 

I will close this issue: as you are publishing at the same time, it seems to me unavoidable. Just difficult to follow , if you want so.

**Comment by bebraw** [comment]
@h2m2 No worries. Note that I have the finished project [here](https://github.com/survivejs-demos/webpack-demo).

I would recommend developing against Node 6 as webpack-dev-server has issues with 7.

I also keep an eye on the [chat](https://gitter.im/survivejs/webpack) if you have some specific questions. I'm pretty keen on improving the content as I'm steadily going towards a paper release (hard to fix then 👍).

I think I have to generate a checkpoint per chapter eventually. Now it's a little tough to jump in.
