### ISSUE TITLE
Does this hmr work on Windows??? 

### ISSUE THREAD

**Issue by h2m2** [survivejs/webpack#146]
I am referring to  the hmr chapter ... I tried the configurations and they did not work out. 
I had to press refresh and in essence that is no hot module reload. 
I can even achieve a clean console. But certainly not a hot reload. 

Child html-webpack-plugin for "index.html":
webpack: bundle is now VALID.
webpack: bundle is now INVALID.

hild html-webpack-plugin for "index.html":
webpack: bundle is now VALID.

It switches its state when you press Ctrl s , but I do need to refresh - to me, the hmr on windows (10) does not work. 

webpack.config.js
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const webpack = require('webpack')

const PATHS = {
    app: path.join(__dirname, 'app'),
    build: path.join(__dirname, 'build')
};

const common = {
// Entry accepts a path or an object of entries.
// We'll be using the latter form given it's
// convenient with more complex configurations.
//
// Entries have to resolve to files! It relies on Node.js
// convention by default so if a directory contains *index.js*,
// it will resolve to that.
    entry: {
        hmr: [
        // Include the client code.
        // Note how the host/port setting maps here.
        'webpack-dev-server/client?http://localhost:8080',

        // Hot reload only when compiled successfully
        'webpack/hot/only-dev-server'

        // Alternative with refresh on failure
        // 'webpack/hot/dev-server',
  ],

       app: PATHS.app,
    },
    output: {
        path: PATHS.build,
        filename: '[name].js',
    },
    plugins: [
    new HtmlWebpackPlugin({
    title: 'Webpack demo',
    }),
    ],
}

const developmentConfig = {
    devServer: {
        watchOptions: {
        // Delay the rebuild after the first change
        aggregateTimeout: 300,
        // Poll using interval (in ms, accepts boolean too)
        poll: 1000,
        },
// Enable history API fallback so HTML5 History API based
// routing works. This is a good default that will come
// in handy in more complicated setups.
    historyApiFallback: true,
// Unlike the cli flag, this doesn't set
// HotModuleReplacementPlugin!
    hot: true,
// Don't refresh if hot loading fails. If you want
// refresh behavior, set inline: true instead.
    hotOnly: true,
    //inline: true,
// Display only errors to reduce the amount of output.
    stats: 'errors-only',
// Parse host and port from env to allow customization.
//
// If you use Vagrant or Cloud9, set
// host: options.host || '0.0.0.0';
// 0.0.0.0 is available to all network devices
// unlike default `localhost`.
    host: process.env.HOST, // Defaults to `localhost`
    port: process.env.PORT, // Defaults to 8080
    },
    plugins: [
   // ignore node_modules so CPU usage with poll watching drops significantly
    new webpack.WatchIgnorePlugin([
        path.join(__dirname, 'node_modules')
    ]),

// Enable multi-pass compilation for enhanced performance
// in larger projects. Good default.
   new webpack.HotModuleReplacementPlugin({
// Disabled as this won't work with html-webpack-template yet
//   multiStep: true,
   }),
   new webpack.NamedModulesPlugin()
    ],
}

module.exports = function(env) {
    //console.log('env', env)
    //return common
    if (env === 'production') {
        return common;
    }
    return Object.assign(
        {},
        common,
        developmentConfig,
        {
            plugins: common.plugins.concat(developmentConfig.plugins),
        }
)
}

package.json
{
  "name": "webpackdemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    
    "start": "nodemon --watch webpack.config.js --exec \"webpack-dev-server --env development\"",
    "build": "webpack"
  
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "html-webpack-plugin": "^2.26.0",
    "nodemon": "^1.11.0",
    "webpack": "^2.2.0-rc.0"
  }
}

**Comment by bebraw** [comment]
Can you push your project on GitHub so it's easier to debug?

**Comment by h2m2** [comment]
I am too stupid for that, ... I will try.  So with one mistake: the component.js and index.js are under an /app directory. At least the files are there.... sorry.

https://github.com/h2m2/webpack

My current assumption is much simpler: I do not believe that the webpack "feels well". It may miss modules. because the complete set of node_modules is not part of the directory.  E.g. when I change 
'webpack-dev-server/client?http://localhost:8080', to 
'webpack-dev-server/?client?http://localhost:8080',  the engine says, it cannot find fs. 

... 

anyway.... the youtube videos are not smarter than your git  ... 
Thanks very, very much for looking at it.

**Comment by bebraw** [comment]
@h2m2 Ok, try my repo and see how it goes. I don't have any Windows specific configuration there, though.

`webpack-dev-server/?client` won't work as an entry point as then it will pass `client` string as a parameter to `webpack-dev-server` module. That's what the error implies too.

This is the main reason why I prefer to run the dev server in inline mode, less hassle. I mentioned the entry alternative as you see that online, but most likely you can skip the WDS entries as the book setup does the same work for you.

**Comment by h2m2** [comment]
Your first sentence , I think it says, it should work for windows like any other computer.

The webpack-dev-server/?client  I did not understand correctly and will correct....

I will test....

**Comment by h2m2** [comment]
https://github.com/h2m2/corrected-Webpack 

is an updated repository  with coorect structure. What I cannot find is a mistake. I just follow the book.

**Comment by bebraw** [comment]
Which editor are you using btw? I'll try checking the setup against a VM today to get a better idea.

**Comment by h2m2** [comment]
I am a user of visual studio code  ... and I can highly recommend it. 
But here is a result of my tests : and it works as far as I think it is ment to be tested. 

package.json:   the build made a change: 
  "scripts": {
    "start": "nodemon --watch webpack.config.js --exec \"webpack-dev-server --env development\"",
    "build": "webpack --env production"
  },

and webpack.config.js is at the state of the book , chapter 2.4 automatic refresh. 
This chapter explains first the package.json.  Then I am supposed to change in my components.js file the line with the wording . I do this and Ctrl s and voilà: it works. As far as I understand this is to be tested and it does the job. 


webpack.config.js: 
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const FriendlyErrorsWebpackPlugin = require('friendly-errors-webpack-plugin')
const PATHS = {
    app: path.join(__dirname, 'app'),
    build: path.join(__dirname, 'build')
};

const common = {
    entry: {
       app: PATHS.app,
    },
    output: {
        path: PATHS.build,
        filename: '[name].js',
    },
    plugins: [
         new FriendlyErrorsWebpackPlugin(),
        new HtmlWebpackPlugin({
        title: 'Webpack demo',
        }),
    ],
}

module.exports = function(env) {
    console.log('env', env)
    return common
}

**Comment by h2m2** [comment]
Good morning, 

I am adicted to visual studio code  - it has its own terminal and is in general super cool. 

https://github.com/h2m2/corrected-Webpack   

It works. AND it is 100% the status of the book at chapter 2.4  ! 
It works means: I believe I should change in components.js
 element.innerText = ' Here I am. \'Rock you like a hurricane. (What a text.).'
to 
 element.innerText = ' Here I am. \'Rock you like a hurricane. '
and Ctrl s. 
The text refreshes. The console is 100% clean - no feedback. 
I receive 
Hash: 1d5d9ab9e9391e008b4d
Version: webpack 2.2.0-rc.0
Time: 30ms
 Asset     Size  Chunks             Chunk Names
app.js  3.59 kB       0  [emitted]  app
chunk    {0} app.js (app) 745 bytes [entry] [rendered]
    [0] ./app/component.js 167 bytes {0} [built]
     + 1 hidden modules
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 541 kB [entry]
         + 4 hidden modules
webpack: bundle is now VALID.

from the friendly error report module... 

Based on this, the code base may have changed  - I am 100% on chapter 2.4. Only your book. Literally.

**Comment by h2m2** [comment]
Exactly like described: as soon as I enter this hmr configuration , I do get some messages as described
[HMR] Waiting for update signal from WDS...
app.js:4110 [WDS] Hot Module Replacement enabled.
app.js:4110 [WDS] Warnings while compiling.

But I do need to refresh. This is exactly the behavior of 3.1 of the book. BUT:
inline or not - no result here.  I do need to refresh.

**Comment by bebraw** [comment]
Hi,

Compared to the [chapter](http://survivejs.com/webpack/developing-with-webpack/configuring-hmr/), quite a bit of configuration is missing.

Can you check your terminal for those warnings? I don't think I've seen that message ever before.

There are many ways to configure HMR and you need to get only one thing wrong for it to fail.

**Comment by h2m2** [comment]
No question about this: the hmr configuration you refere to is "3.1 in the book". 

This configuration fails  - but the hmr in the sense described works with the configuration given. 

So here is my terminal output:   it is a valid bundle
[nodemon] restarting due to changes...
[nodemon] starting `webpack-dev-server --env development`
keywords if/then/else require v5 option
 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from G:\Programmierung\dies und das\webpackdemo
404s will fallback to /index.html
Child html-webpack-plugin for "index.html":

webpack: bundle is now VALID.


The console in the browser gives me: 
[HMR] Waiting for update signal from WDS...

Result: need to refresh the browser. 

I update the github repo to your required webpack.config.js in one minute - just after commiting this comment.
https://github.com/h2m2/corrected-Webpack

**Comment by h2m2** [comment]
commited the change - (in my view not required as webpack like chapter 2.4 does the job already.).

**Comment by bebraw** [comment]
If you update a file, what happens at the browser?

I think you should be able to skip `'webpack/hot/dev-server'` line at your configuration as you have what's needed at the `devServer` portion.

What kind of behavior do you get against the reference project?

**Comment by h2m2** [comment]
I do use the reference project .... now I check you variant. I did not test that one.....
but it does not do it.   The simple version currently contains the hmr, if I were asked: that is the implementation for this week.... 

The browsers shows zero reaction: the console is completely empty. 
I uses this config according to your last remarks: 


const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const webpack = require('webpack')

const PATHS = {
    app: path.join(__dirname, 'app'),
    build: path.join(__dirname, 'build')
};

const common = {

    entry: {
            app: PATHS.app,
    },
    
    output: {
        path: PATHS.build,
        filename: '[name].js',
    },
    
    plugins: [
    new HtmlWebpackPlugin({
    title: 'Webpack demo',
    }),
    ],
}
//#################  this is the portion, I tried out ###############
const developmentConfig = {
    devServer: {
    
   historyApiFallback: true,
   hot: true,
   hotOnly: true,
   // inline: true,
    stats: 'errors-only',
    host: process.env.HOST, // Defaults to `localhost`
    port: process.env.PORT // Defaults to 8080
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin({
        }),
        new webpack.NamedModulesPlugin()
    ]
}


module.exports = function(env) {
    //console.log('env', env)
    //return common
    if (env === 'production') {
        return common;
    }
    return Object.assign(
        {},
        common,
        developmentConfig,
        {
            plugins: common.plugins.concat(developmentConfig.plugins),
        }
)
}

**Comment by bebraw** [comment]
@h2m2 Ok. I'm just setting up a VM so I can see better what's going on.

**Comment by bebraw** [comment]
I managed to get [this boilerplate](https://github.com/AngularClass/angular2-webpack-starter) running there, but the book one fails (errors if I run it through `npm start` or terminates execution through a direct invocation).

The good thing is that now I have something to debug. Thanks for bringing this up.

**Comment by h2m2** [comment]
No issue at all. 
Overall, I am very happy with webpack. Also with the book. From what I hear, many people like both.
:-))
have a good Sunday.

**Comment by bebraw** [comment]
@h2m2 I went through the setup on Windows 10 (VM). I definitely see output at console and the setup works like in the book without any extra tweaks that are discussed later in the chapter.

I also got your project to run. Note that I fixed webpack and webpack-dev-server to 2.2.0 there (latter was missing from the project, maybe that was the problem?). Could you try `npm install webpack-dev-server@beta -D` against the project and try running it again? Also a screenshot of console output would help.

**Comment by h2m2** [comment]
Hi.

I know , you are angry with me, that I did not come back in time.  So here is my report, why I will be very, very carefull with webpack and why it is impossible to e.g. ask you for help.   

To start with I did also check my install ......   a complete failure. 
I did install v 1.x    silently. Not 2. 
It was a shock. I needed my time.

So , I went back and tried a bit of installation - I started to get errors. unmet peer dependencies etc. 
So, I unchecked step by step the webpack.config.js and the package.json. 
Not only are they both in the way of a new install, also unchecking them is in the way....

You do need an entirely new mkdir and you npm init. 
So I did that and move through a couple of installs 

npm i webpack@1.4.0-beta9    (ok )
npm i webpack@1.9.11	(ok)
npm i webpack@2.1.0-beta13  (ok)
npm i webpack@^2.2.0-rc.7	(ok)
npm i webpack-dev-server@2.2.0-rc.0  (ok)

I still do not know , if I do have the webpack-dev-server@2.2.0-rc.0 or in addition webpack@^2.2.0-rc.7. 
I relaxed and thought about it. 

webpack@^2.2.0-rc.7

npm i webpack-dev-server@2.2.0-rc.5  was an error and the engine give the feedback that explicitely rc.0 is valid.
Your book does not say so. 
Not only is webpack a little bit complex, but I cannot find siltently discarded install nonsense. 

So I checked through some other issues. 

Where is the consistency and where is the documentation? Example: 

exports.extractCSS = function(paths) {
    return {
        module: {
            rules: [
            // Extract CSS during build
                {
                test: /\.css$/,
                // Restrict extraction process to the given paths.
                include: paths,
                loader: ExtractTextPlugin.extract({  // here you will find use. But with this Plugin not - loader.
                    fallbackLoader: 'style-loader',  // never found - found in the wild
                    loader: 'css-loader',            // here loader and not use ?
                    'css?modules&importLoaders=0&localIdentName=[path]___[name]__[local]___[hash:base64:5]'
// is importLoaders=0 valid?
// &importLoaders=1 is valid, if you end the line with   [hash:base64:5]!postcss-loader' 
// but I could not find it                    
// what follows is equivalent - but I never found it.
//options: {
                        //  modules: true,
                        //  sourceMap: true,
                        //  importLoaders: 1 - for !postcss-loader  and where to place this
                        //  localIdentName: '[path][name]__[local]--[hash:base64:5]'

                }),

css modules is an urgent example.  I could also not understand where to place the plugins - sometime I find them in the config, sometimes in the parts.  Also not consistent. And for me, to hard to understand.

webpack is not only complex.
webpack is quite an adventure, certainly not for the faint heart like me, as I would gracefully call this an inconsistent pile of greatness ( I am far from judging the code and the design: genious , no doubt. But not applicable for average guys like me: I read, I try to follow. I find a breadth and depth of inconsistencies that I cannot surmount.  ) 

That is , why I need to stop: it is for an average guy like me, two miles too high.
I will somehow hack it together. At the end of the day, I need a few things from it and I will get them in the end. But I cannot identify it as industrial quality.   .... It bites me. And I need to code, not to configure.

Cheers.

**Comment by bebraw** [comment]
> I know , you are angry with me, that I did not come back in time. So here is my report, why I will be very, very carefull with webpack and why it is impossible to e.g. ask you for help.

Nah, I'm not angry. I know people are busy etc. I found a couple of weak spots thanks to the thread and now I have a Windows VM running for testing. 👍 

> I did install v 1.x silently. Not 2.

It is important to note that webpack 2 is available through the beta channel (`npm i webpack@beta`) at the moment. `npm i` would give webpack 1. This was due to a grace period as we released it only a week ago. We'll most likely make `latest` point at webpack 2 today so it will give you the version you expect. This applies to webpack-dev-server and certain plugins too.

> npm i webpack-dev-server@2.2.0-rc.5 was an error and the engine give the feedback that explicitely rc.0 is valid.

The final 2.2.0 of webpack-dev-server should fix the peer dependency warnings.

> Where is the consistency and where is the documentation? Example:

ExtractTextPlugin is a tricky one as it consists of a loader an a plugin. To make things worse, the current beta version behaves in an inconsistent way although that should be fixed as it gets to a stable version.

> css modules is an urgent example. I could also not understand where to place the plugins - sometime I find them in the config, sometimes in the parts. Also not consistent. And for me, to hard to understand.

There are no hard rules. You could skip the part abstraction altogether and build one giant configuration. Nothing wrong with that if composition isn't a concern.

--

You probably chose the worst time to dig into webpack. Things are especially bumpy now as the project reached a major milestone with its 2.2 release. Those `@beta` things, extract-text-plugin, enhanced configuration model (more complex, but also more powerful), add up.

Feel free to revisit the book later. I expect it might be a little easier to get into webpack then. The initial learning curve is quite steep, but once you get past it, there's not much left to climb.

All the best.
