### ISSUE TITLE
Separating CSS chapter: Suggestion: Add autoprefixer to extractCSS

### ISSUE THREAD

**Issue by jeggett** [survivejs/webpack#155]
Section 'Setting Up extract-text-webpack-plugin'. What do you think about adding autoprefixer to `extractCSS` part? I think this pllugin it's such a common thing in production builds. Not necessary the autoprfixer plugin but any postcss plugin like cssnano or smth. would be nice too. 

PS
Currently it's not clear where I should plug it. Below is code snippet where I marked with comments places where I could add it, but I am not sure where this part with postcss-autoprefixer should go to work along with ExtractCSS plugin.
```
exports.extractCSS = function extractCSS(paths) {
  return {
    module: {
      rules: [
        {
          test: /\.(scss|css)$/,
          include: paths,
          use:
            // Plug it here using the syntax as in http://survivejs.com/webpack/handling-styles/loading/#postcss ?
            ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: ['css-loader?sourceMap', 'sass-loader?sourceMap'], // Or plug it into this array like `postcss?someQueryParams ?
          }),
        },
      ],
    },
    plugins: [
      // Output extracted CSS to a file
      new ExtractTextPlugin('[name]_[contenthash].css'),
    ],
  };
};
```

**Comment by bebraw** [comment]
Yeah. This is a good point. It's worth adding as the setup is non-trivial.

`ExtractTextPlugin` API needs a more comprehensive explanation anyway and it's going to change a notch before the final release.
