### ISSUE TITLE
Glob pattern for purifycss

### ISSUE THREAD

**Issue by galenus** [survivejs/webpack#178]
In chapter ['eliminating unused css'](https://github.com/survivejs/webpack/blob/dev/manuscript/handling_styles/03_eliminating_unused_css.md) the glob pattern should be `appPath/**/*` and not `appPath/*`. Otherwise, nested folders will not be traversed.

**Comment by bebraw** [comment]
Fixed. Thanks. 👍 

Let me know if you want to be listed in thanks.

**Comment by galenus** [comment]
No, I'm good.
Generally, don't you think the paths passed to the plugin should be filtered to those of files only?

**Comment by bebraw** [comment]
> Generally, don't you think the paths passed to the plugin should be filtered to those of files only?

It could be constrained to JavaScript files since we want to track the usage. So a pattern like `**/*.js` would be nice here.

**Comment by bebraw** [comment]
I added `verbose` flag to the plugin if you want to see what it's doing underneath. There are also a couple of other [options](https://github.com/webpack-contrib/purifycss-webpack#options).

I have to give the plugin more attention once I'm a bit less busy with the book and I'm willing to tweak the API naming etc. as needed.
