### ISSUE TITLE
Generating index.html for SPAs

### ISSUE THREAD

**Issue by cesarandreu** [survivejs/webpack#25]
This is something that I struggled with when I first picked up webpack as well, since I wanted my production and development scripts to be as similar as possible.

Currently I use a custom plugin that will receive the stats object, extract the JS and CSS list, and pass it to an `Html.jsx` file.

I recently found [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin), but haven't tried it.

**Comment by bebraw** [comment]
Yeah, good point. `html-webpack-plugin` is excellent for this purpose. It has matured a lot lately and is definitely worth covering.

**Comment by bebraw** [comment]
It's covered in the new [Getting Started](http://survivejs.com/webpack/developing-with-webpack/getting-started/) chapter.
