### ISSUE TITLE
 Hot Module Replacement is disabled 

### ISSUE THREAD

**Issue by chbinghu** [survivejs/webpack#42]
I got this error when use weppack-dev-server for automatically refresh.
Uncaught Error: [HMR] Hot Module Replacement is disabled.
dev in package.json is 
"dev": "webpack-dev-server --devtool eval --progress --colors --hot --content-base build" 
entry in webpack.config.js is
entry: ['webpack/hot/dev-server', path.resolve(__dirname, 'main.js')],
How to deal with that?

**Comment by bebraw** [comment]
It's impossible to tell without seeing some code. There's likely something preventing it from working. If you go without `--inline`, you may need an entry like `'webpack-dev-server/client?http://localhost:3000'` assuming that's the port you are using.

Can you try my setup covered at [Developing with Webpack](http://survivejs.com/webpack_react/developing_with_webpack/) and [Webpack and React](http://survivejs.com/webpack_react/webpack_and_react/)? I maintain that actively.
