### ISSUE TITLE
Using inline styles instead of stylesheets

### ISSUE THREAD

**Issue by danpalmer** [survivejs/webpack#51]
I was reading the cookbook, and just noticed this section.

Unless Webpack is doing something really sneaky here (which I don't think is the case, but do correct me if I'm wrong), these styles will end up being rendered into the page as inline styles on DOM elements.

This is generally poor for application security. Aspects of inline styles can be used in various attacks, including XSS attacks, and it's generally preferable to disable them with a [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) if possible.

I advise adding a warning to this section to say that it could cause security issues, and that it is not advised to use it in production.

**Comment by bebraw** [comment]
Correct. It's preferable to use [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) for production. I describe one way to use that at [my book](http://survivejs.com/webpack_react/building_kanban/#separating-css).

**Comment by tsaiDavid** [comment]
@bebraw @danpalmer - could using things like 'Radium' help mitigate these potential security issues?

**Comment by bebraw** [comment]
@tsaiDavid Good question. Perhaps it would be the best to ask from the [Radium](https://github.com/FormidableLabs/radium) guys directly. Feel free to CC me. :+1:

**Comment by bebraw** [comment]
@tsaiDavid Did you ask the Radium guys? I wonder how they deal with this.
