### ISSUE TITLE
Example combining both sections in Authoring Libraries?

### ISSUE THREAD

**Issue by saschwarz** [survivejs/webpack#60]
As a new user one of the biggest challenges I find in using webpack is producing all the permutations of output in a single configuration. It would be great to see an example of a configuration that supports script and npm packaging of a library as is described using Browserify in this blog post:
http://krasimirtsonev.com/blog/article/distributing-react-components-babel-browserify-webpack-uglifyjs

Thanks for this very helpful cookbook.

**Comment by bebraw** [comment]
Could you have a look at [Authoring Packages](http://survivejs.com/webpack/advanced-techniques/authoring-packages/) and see if that's close enough now?

**Comment by bebraw** [comment]
I'm going to close this now. If this gets relevant again, please poke.
