### ISSUE TITLE
absolute path import doesn't work

### ISSUE THREAD

**Issue by eyalw** [survivejs/webpack#62]
hey, it seems absolute import doesnt work for me. what happens is that webpack translates the require('/whatever') to a url, and my server tries to load it, instead of webpack importing it.
https://github.com/christianalfoni/react-webpack-cookbook/wiki/Requiring-files

  entry: [
    './client/scripts/index.js',
    'webpack-hot-middleware/client',
  ],

**Comment by bebraw** [comment]
Did you manage to resolve this? If you want `require('whatever')`, you can set [resolve.root](https://webpack.github.io/docs/configuration.html#resolve-root).

I'm currently rewriting the book btw. As that particular chapter went away and the statement isn't there anymore, I'm closing this. Feel free to continue conversation, though.
