### ISSUE TITLE
Multi entry points with react hot loader

### ISSUE THREAD

**Issue by StanBoyet** [survivejs/webpack#65]
Hi,

I found your post about multi entry points really useful (https://github.com/christianalfoni/react-webpack-cookbook/wiki/Multiple-entry-points).

But in your post about hot loading components (https://github.com/christianalfoni/react-webpack-cookbook/wiki/Hot-loading-components), no more mentions of multi entry points. Would you have an example laying around about this one ? :) Can't find a way to make it work. It seems that my HMR is never triggered.

Thanks !

**Comment by bebraw** [comment]
Can you set up an example for me to study? I've revised the book a lot btw. Here's [a revised React portion](http://survivejs.com/webpack/advanced-techniques/configuring-react/).

**Comment by bebraw** [comment]
Going to close this one. Please poke me again if this is relevant and I'll look into it.
