### ISSUE TITLE
Transfer below survivejs organization

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack#66]
Just opening this so we can track the status of migration:

- [ ]  Figure out how to deal with redirects. Each page should point to a new one on survivejs.com site so we don't break the internet. Basically each old page needs something like `<meta http-equiv="refresh" content="0; url=http://example.com/" />`.
- [ ]  Make sure [survivejs site](https://github.com/survivejs/site) can pick up the material. We'll probably end up with `/webpack_cookbook` and pages below that.
- [ ]  Assuming the first two have been completed, switch over. After that I'll go through the issues and try to resolve as many as I can. The content needs some other tweaks as well.

@christianalfoni Sounds good?

**Comment by bebraw** [comment]
@christianalfoni Any thoughts? I can do most of the work, set up redirects etc.

**Comment by christianalfoni** [comment]
Actually I think this just works when we transfer the repo. Though just a fix to github pages? https://help.github.com/articles/transferring-a-repository/. If you let me know when you are ready I am happy to do a transfer of the repo to survivejs :-)

**Comment by bebraw** [comment]
Yeah. Most of it will work for sure.

I meant redirects like

* From: https://christianalfoni.github.io/react-webpack-cookbook/Introduction-to-Webpack.html
* To: http://survivejs.com/webpack_cookbook/introduction

This is something I'll need to resolve carefully so we don't break any links. I'll provide you a repo that you can push to old `react-webpack-cookbook` repo with `gh-pages` so that it will redirect and we don't break the internet. :+1:

I'll try to get this done next week. I'll be in touch then again.

**Comment by christianalfoni** [comment]
Awesome :+1: :)
