### ISSUE TITLE
Replace React Hot Loader documentation with React Transformer HMR

### ISSUE THREAD

**Issue by michaelguild13** [survivejs/webpack#67]
Replace documentation of Hot loading on React Hot Loader with React Transformer HMR since React Hot Loader is depreciated.

https://github.com/gaearon/react-transform-hmr
EX:https://github.com/gaearon/react-transform-boilerplate

**Comment by bebraw** [comment]
Fixed. See [Configuring React](http://survivejs.com/webpack/advanced-techniques/configuring-react/).
