### ISSUE TITLE
How to output vendor.min.js with hash generated based on content?

### ISSUE THREAD

**Issue by lomotony** [survivejs/webpack#70]
I split bundle.min.js and vendor.min.js in production environment, but i want to add the hash to the file for vendor.min.js less changed.

**Comment by bebraw** [comment]
I have explained it [here](http://survivejs.com/webpack/building-with-webpack/adding-hashes-to-filenames/). I hope that helps! Note that the chapter relies on a setup built on the earlier ones so you might need to look those up to see how it all goes together.
