### ISSUE TITLE
[Mistake] Splitting Bundles - Object.keys(pkg)

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack#76]
http://survivejs.com/webpack/building-with-webpack/splitting-bundles/

> It can be convenient to define a vendor entry based on package.json dependencies. Load the file first using const pkg = require('./package.json'); and then do vendor: Object.keys(pkg).

It should be either `pkg = require('./package.json').dependencies` or `vendor: Object.keys(pkg.dependencies)` right?

**Comment by bebraw** [comment]
Correct. Thanks for pointing this out. I'll get it fixed for the next release.
