### ISSUE TITLE
[Mistake] Cleaning build - Preserving .dotfiles

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack#77]
http://survivejs.com/webpack/building-with-webpack/cleaning-build/

> If you want to preserve possible dotfiles within your build directory, you can use [path.join(PATHS.build, '/*')] instead of [PATHS.build].

Will it work? Because we are passing the argument as a string, and turning it into an array for the plugin inside the `.clean` function. So if we pass an array, it will get passed as a nested array to the plugin. Maybe it would be better to pass an array in the first place?

**Comment by bebraw** [comment]
That's a valid point. I'll simplify that statement and forget about the array. 👍
