### ISSUE TITLE
Discuss npm --save-exact?

### ISSUE THREAD

**Issue by bebraw** [survivejs/webpack#84]
> “If you want to save an exact version of a dependency, use --save-exact. The shortcut for this is -E. If you install a dependency like this, npm skips using the default SemVer operator.”

To quote @TomByrer:

> A bit of a jump. Though most programmers know what a 'version' is, if you have to explain what npm is, they are unlikely to know what 'SemVer' is & what that carrot means. Likely will need a page of its own; or just remove to prevent rabbit trails.

https://github.com/survivejs/webpack_react/issues/390

Just moving the issue here so I won't lose track of it.

**Comment by alejandronanez** [comment]
Maybe mentioning npm shrinkpack is worth here.

**Comment by bebraw** [comment]
Ah, yeah. [shrinkpack](https://github.com/JamieMason/shrinkpack) would fit the npm chapter.
