### ISSUE TITLE
webpack: how to ordering dependencies  between entries

### ISSUE THREAD

**Issue by Trispa** [survivejs/webpack#85]
in my webpack config file I have two multy entries:

```
module.exports = {
      entry:{
             lib:["./scripts/file1.js","./scripts/fil2.ts"],
             app:["./scripts/login.js","./public/HSplitLayout.js"]
      },
      output: {
        path: 'builds',
        filename: '[name].js',
        publicPath: 'builds/',
        libraryTarget: "var"
    }
}
```
I want to ensure that the lib.js file is completely loaded before app.js is loaded.

Thank you for your help

**Comment by bebraw** [comment]
Are you using html-webpack-plugin? I think it should pick up the script tag order from the definition.

**Comment by Trispa** [comment]
thansk @bebraw  i't work well now. thanks a lot
