### ISSUE TITLE
Loading Fonts - prefix query has no effect

### ISSUE THREAD

**Issue by vjancik** [survivejs/webpack#86]
I think the `prefix` query got deprecated or removed, because it no longer works and it's not mentioned in the file-loader [GitHub page](https://github.com/webpack/file-loader).

I've replaced this: 
> `prefix: 'font/',`

with this:
> `name: 'font/[hash].[ext]',`

and it started doing what it was supposed to.

Mentioned in:
http://survivejs.com/webpack/loading-assets/loading-fonts/

Supported by: https://github.com/webpack/file-loader/issues/32

**Comment by bebraw** [comment]
Thanks. I'll get this fixed.
