### ISSUE TITLE
Talk a little more about font loading.

### ISSUE THREAD

**Issue by alejandronanez** [survivejs/webpack#91]
We discuss this today on gitter but I think it's better to write an issue for it so we don't lose track.

Basically add a little more detail on the fonts chapter and maybe mention something like `setupDevelopmentFonts` & `setupProductionFonts`.

**Comment by bebraw** [comment]
Yup. Good move. 👍

**Comment by bebraw** [comment]
Can you check the [current chapter](http://survivejs.com/webpack/loading-assets/loading-fonts/)? I added a couple of more techniques, but I don't mind adding more.

**Comment by bebraw** [comment]
I added a Font Awesome example there too. I guess it's safe to close this. Feel free to open more specific issues if you notice something.
