### ISSUE TITLE
Refreshing CSS - Needs update

### ISSUE THREAD

**Issue by tyler-morrison** [survivejs/webpack#93]
I was trying to follow this section, but kept getting an error whenever I added `require('./main.css')` to index.js.

After tweaking the default switch case within `webpack.config.js` to include PATHS.style, I was able to get everything to work properly.

**Comment by bebraw** [comment]
Thanks for the heads up! I'll get this sorted for the next version.

**Comment by tyler-morrison** [comment]
My apologies, I believe this may be user error. I encountered a similar issue on the Minifying Build chapter and realized that I was using ES6 syntax within `app`, despite not having any transpilers in place.

**Comment by bebraw** [comment]
No probs. Thanks still. :+1:
