### ISSUE TITLE
Analyzing Build Statistics - Code snippet contains leanpub markup

### ISSUE THREAD

**Issue by yoadsn** [survivejs/webpack#96]
The code sample  under `webpack.config.js` contains "leanpub" markup.
Towards the buttom of the code snippet.

**Comment by bebraw** [comment]
I think this has been fixed. See [here](https://github.com/survivejs/webpack/blob/dev/manuscript/building_with_webpack/08_analyzing_build_statistics.md). GitHub doesn't render right, though.

I'll try to get a little patch release (splitting a chapter etc.) out next week. Depends on the workload.

**Comment by bebraw** [comment]
This should be done. Thanks.
