### ISSUE TITLE
ESLint instructions should include `eslint --init`

### ISSUE THREAD

**Issue by shepmaster** [survivejs/webpack#98]
Following the steps in the book:

1. `npm i eslint --save-dev`
1. Add `"test:lint": "eslint . --ext .js --ext .jsx --cache"` to `package.json`
1. `npm run test:lint`

You will get the error:

```
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init
```

The error message is straightforward to fix, but it may be worth including it in the text.

**Comment by bebraw** [comment]
Thanks!
